import Head from 'next/head'
import Image from 'next/image'

import styles from '../page-styles/Home.module.css'
import NotifactionsIcon from '../public/svg/notifactions-icon.svg'
import MessagesIcon from '../public/svg/messages-icon.svg'
import { userData } from '../utils/sampleData'

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Sosmad</title>
      </Head>
      <div className={styles.main}>
        <div className={styles.header}>
          <h1>Sosmad</h1>
          <button>
            <NotifactionsIcon />
          </button>
          <button>
            <MessagesIcon />
          </button>
        </div>
        <div className={styles.stories}>
          <h2>Stories</h2>
          <div className={styles.storiesContainer}>
            <div className={styles.storyPreview}>
              <Image fill
                src='/images/female-1-story.jpg'
                alt='' className={styles.storyImage} />
              <div className={styles.storyTitle}>
                <div className={styles.storyProfile}>
                </div>
              </div>
            </div>
            <div className={styles.storyPreview}>
              <Image fill
                src='/images/female-1-story.jpg'
                alt='' className={styles.storyImage} />
              <div className={styles.storyTitle}>
                <div className={styles.storyProfile}>
                </div>
              </div>
            </div>
            <div className={styles.storyPreview}>
              <Image fill
                src='/images/female-1-story.jpg'
                alt='' className={styles.storyImage} />
              <div className={styles.storyTitle}>
                <div className={styles.storyProfile}>
                </div>
              </div>
            </div>
            <div className={styles.storyPreview}>
              <Image fill
                src='/images/female-1-story.jpg'
                alt='' className={styles.storyImage} />
              <div className={styles.storyTitle}>
                <div className={styles.storyProfile}>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
