import Head from 'next/head'

import styles from '../page-styles/Home.module.css'
import StorySlider from '../components/stories-slider/stories-slider.component'
import Header from '../components/header/header.component'
import { sampleData } from '../utils/sampleData'

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Sosmad</title>
      </Head>
      <div className={styles.main}>
        <Header />
        <StorySlider userDataArray={sampleData} />
      </div>
    </>
  )
}
