import Head from 'next/head'
import React, { useState } from 'react'

import styles from '../page-styles/Home.module.css'
import StorySlider from '../components/stories-slider/stories-slider.component'
import Header from '../components/header/header.component'
import BinarySelector from '../components/binary-select/binary.select.compoent'

import { sampleData } from '../utils/sampleData'
import Post from '../components/post/post.compoent'

export default function Home() {
  const [selectActive, setSelect] = useState(false)

  const selectorOnClick = (option: string) => {
    if (option === 'Explore') {
      return setSelect(false)
    }
    setSelect(true)
  }

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Sosmad</title>
      </Head>
      <div className={styles.main}>
        <Header />
        <StorySlider
          userDataArray={sampleData}
        />
        <BinarySelector
          optionOne='Explore'
          optionTwo='Discover'
          onClickHandle={selectorOnClick}
          stateValue={selectActive}
        />
        <Post />
        <Post />
        <Post />
      </div>
    </>
  )
}
